packages:
    - name: contacts
      shared: false
      environment:
        SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
        SENDGRID_LIST_ID: "${SENDGRID_LIST_ID}"
      parameters: {}
      annotations: {}
      functions:
        - name: email
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
